application: oxystats
version: 2
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /data_.*
  script: main.py
  login: required

- url: /index.html
  script: main.py
  login: required

- url: /script.js
  script: main.py
  login: required

- url: /
  script: main.py
  login: required

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  login: required
